change-type:
    after-string: '] '
    before-string: '['
    destination: title
    instructions: What kind of change?
    modifiable: true
    options:
        - fix
        - add
        - refactor
        - clean
        - meta
    type: select
commit-title:
    destination: title
    placeholder: Commit Title
    type: text
commit-description:
    after-string: ""
    allow-empty: true
    destination: body
    instructions: Please describe your changes.
    type: multiline-text
code-sections:
    after-string: ""
    allow-empty: true
    before-string: "\nCode Sections: "
    destination: body
    instructions: Which section(s) of the codebase?
    modifiable: true
    options:
        - parser
        - option
        - tests
        - docs
    record-as: joined-string
    type: multi-select
ticket-number:
    allow-empty: true
    before-string: "\n\nTicket: "
    data-type: integer
    destination: body
    instructions: Associated Ticket Number (if any)
    type: text
